[project]
name = "photoaddwatermark"
version = "0.3.2"
description = "Add watermark to your photo works automatically."
requires-python = ">=3.12"
dependencies = [
    "piexif>=1.1.3",
    "pillow>=11.3.0",
]
